service: opta-lambda-scrapper
provider:
  name: aws
  runtime: nodejs14.x

functions:
  scraper:
    handler: handler.main
    memorySize: 1536
    timeout: 20
    events:
      - http:
          path: /
          method: get
